apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api 
spec:
  replicas: 1 #Quero sempre 3 Pods

  #O deployment precisa saber quais Pods pertecem a ele
  #Ele usa labels para isso
  selector:
    matchLabels:
      app: mlops-api

  #Observe o Pod recebe a mesma label.
  template:
    metadata:
      labels:
        app: mlops-api 


    spec:
      containers:
      - name: api
        image: samuelpa8x100/mlops-api:latest
        ports:
          - containerPort: 8000

        #Gerenciando recursos
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        #Vê se iniciou beleza
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 30
          periodSeconds: 5
          #Isso permite 30x5 de toleência antes de falhar

        #Vê se a aplicação está pronta para receber tráfego
        readinessProbe:
          httpGet: #Fará= GET http://container:8000/health
            path: /health
            port: 8000
          initialDelaySeconds: 5 #Espera 5s antes de começar a verificar
          periodSeconds: 10 #Verifica a cada 10 segundos

        #Vê se a aplicação está viva
        livenessProbe: #Vê se okay e manda tráfego
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 20



        envFrom:
        - configMapRef:
            name: mlops-config
        - secretRef:
            name: mlops-secret