"""Criandocolunacomlayssa

Revision ID: c4708257cfae
Revises: d45fa5a27ceb
Create Date: 2026-08-02 02:35:35.920872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4708257cfae'
down_revision: Union[str, Sequence[str], None] = 'd45fa5a27ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('previsoes', sa.Column('horario', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('previsoes', 'horario')
    # ### end Alembic commands ###
