"""Criando nova voluna nUlll tru

Revision ID: d45fa5a27ceb
Revises: 8812daf9ed5e
Create Date: 2026-08-01 14:13:45.852309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd45fa5a27ceb'
down_revision: Union[str, Sequence[str], None] = '8812daf9ed5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('previsoes', sa.Column('versao', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('previsoes', 'versao')
    # ### end Alembic commands ###
