"""Criando tabela previsoes

Revision ID: e8336af6b56f
Revises: 
Create Date: 2026-08-10 17:14:35.419301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8336af6b56f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('previsoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(length=20), nullable=True),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('quartos', sa.Integer(), nullable=False),
    sa.Column('banheiros', sa.Integer(), nullable=False),
    sa.Column('garagem', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previsoes')
    # ### end Alembic commands ###
