name: CI
on:
  push:
    branches:
      - master

jobs:

  #Git cria uma máquina ubuntu não precisa configurar nada.
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: baixa_repositorio
        uses: actions/checkout@v4 #Baixa o seu repositório

      - name: python_na_maquina
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install
        run:  |
          pip install -r requirements.txt


      - name: Test 
        run:  |
          python3 -m pytest tests/test_api.py -v

      - name: Coverage
        run: |
          python3 -m pytest --cov=api

      - name: Build Docker
        run: |
          docker build -t mlops-api .

      #Até aqui é no desenvolvimento
      #Depois, para deploy    

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and Push 
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mlops-api:latest